CLASS zbp_r_yaipoheader DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_yaipoheader.

PUBLIC SECTION.
PROTECTED SECTION.
PRIVATE SECTION.
ENDCLASS.


CLASS zbp_r_yaipoheader IMPLEMENTATION.
ENDCLASS.
